### ISSUE TITLE
Striped digital noise

### ISSUE THREAD

**Issue by kantsche** [CapsAdmin/ComfyUI-Euler-Smea-Dyn-Sampler#1]
There is this striped noise I dont know if it comes from this or from the sampler.
![ShadowPCDisplay_1EP8lhvStl](https://github.com/CapsAdmin/ComfyUI-Euler-Smea-Dyn-Sampler/assets/5844962/ef45a461-d507-4aa6-b6fc-c1a50c01e435)

**Comment by CapsAdmin** [comment]
I'm not sure, but the original author incorporated this node into their repo, see:

https://github.com/Koishi-Star/Euler-Smea-Dyn-Sampler

I'll archive this and update the readme

Try using that first and if the issue still persist open an issue there
